# Generated by Django 5.0.6 on 2025-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_product_code_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
