# Generated by Django 5.0.6 on 2025-01-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
