# Generated by Django 5.0.6 on 2025-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=121),
            preserve_default=False,
        ),
    ]
